### ISSUE TITLE
Using wottactics without social sign-in

### ISSUE THREAD

**Issue by ImVeryVeryStupid** [karellodewijk/wottactics#1]
Is it possible to use wottactics without social sign-in on your own server?
As far as I've found out empty passwords don't really work and made up password spew up errors as well. It's kinda big effort to rack up on useless accounts just for option to log in when I can just hide all of this under the forum pages. So any suggestions or am I just doing something really stupid here?

Some errors:

With empty id's and passwords in secrets.txt:
`stupid@testbed:/var/www/idontowndomain.com/tactics$ sudo node app.js
Connecting to:  127.0.0.1:27017/wottactics
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/var/www/idontowndomain.com/tactics/node_modules/passport-vkontakte/node_modules/passport-oauth2/lib/strategy.js:83:34)
    at new Strategy (/var/www/idontowndomain.com/tactics/node_modules/passport-vkontakte/lib/passport-vkontakte/strategy.js:56:18)
    at /var/www/idontowndomain.com/tactics/app.js:363:21
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1504:5
    at handleCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/utils.js:96:12)
    at _callback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1420:5)
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1463:7
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1415:5
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/auth/mongocr.js:113:17
    at commandCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1193:9)
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/var/www/idontowndomain.com/tactics/node_modules/passport-vkontakte/node_modules/passport-oauth2/lib/strategy.js:83:34)
    at new Strategy (/var/www/idontowndomain.com/tactics/node_modules/passport-vkontakte/lib/passport-vkontakte/strategy.js:56:18)
    at /var/www/idontowndomain.com/tactics/app.js:363:21
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1504:5
    at handleCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/utils.js:96:12)
    at _callback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1420:5)
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1463:7
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1415:5
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/auth/mongocr.js:113:17
    at commandCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1193:9)`

With made up id's and passwords in secrets.txt:
`stupid@testbed:/var/www/idontowndomain.com/tactics$ sudo node app.js
Connecting to:  127.0.0.1:27017/wottactics
TypeError: Cannot read property 'client_id' of undefined
    at /var/www/idontowndomain.com/tactics/app.js:386:30
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1504:5
    at handleCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/utils.js:96:12)
    at _callback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1420:5)
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1463:7
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1415:5
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/auth/mongocr.js:113:17
    at commandCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1193:9)
    at Callbacks.emit (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:358:23)
TypeError: Cannot read property 'client_id' of undefined
    at /var/www/idontowndomain.com/tactics/app.js:386:30
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1504:5
    at handleCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/utils.js:96:12)
    at _callback (/var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1420:5)
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb/lib/db.js:1463:7
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1415:5
    at /var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/auth/mongocr.js:113:17
    at commandCallback (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:1193:9)
    at Callbacks.emit (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/var/www/idontowndomain.com/tactics/node_modules/mongodb-core/lib/topologies/server.js:358:23)`

**Comment by karellodewijk** [comment]
Nah, you're not doing something very stupid, I just didn't make it very user friendly.

Anyway, I just made the login options optional within the server, so it should no longer halt if you leave the client_id's in secrets.txt empty. Those login options will ofcourse not work. You will need to fill in valid info for a mongo database and a redis server though at the very least.

There are actually some other changes I need to make to properly run this properly on another host, I'll make some work of it tomorrow. But I think it's best if you just get in touch.

**Comment by karellodewijk** [comment]
Ok, I just committed some changes that should make it a lot easier to get started. I updated the readme file accordingly.

It could very well be I forgot something though, if you have any more issues let me know.
