### ISSUE TITLE
Error: no hostname or hostnames provided in connection string

### ISSUE THREAD

**Issue by KongGal** [karellodewijk/wottactics#3]
```
Error: no hostname or hostnames provided in connection string
    at module.exports (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/url_parser.js:22:11)
    at connect (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/mongo_client.js:403:16)
    at Function.MongoClient.connect (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/mongo_client.js:227:3)
    at Object.<anonymous> (/var/www/vhosts/suicide-squad.cc/app.js:100:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Error: no hostname or hostnames provided in connection string
    at module.exports (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/url_parser.js:22:11)
    at connect (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/mongo_client.js:403:16)
    at Function.MongoClient.connect (/var/www/vhosts/suicide-squad.cc/node_modules/mongodb/lib/mongo_client.js:227:3)
    at Object.<anonymous> (/var/www/vhosts/suicide-squad.cc/app.js:100:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

I filled out both username and password for mongodb created with the db.createuser but what should be filled in the mongo_string? in secrets.txt?

**Comment by karellodewijk** [comment]
Hi Kongal

It depends on where you mongo database is hosted. If it's on the same computer as the app is running,  on the default port, fill in "localhost:27017/db_name".

**Comment by karellodewijk** [comment]
So if you are following the readme: "localhost:27017/wottactics"

**Comment by KongGal** [comment]
Ah yeah that did it, Maybe an idea to add to the readme :)

Also when adding a wg API key and trying to login i just get this in the console
(node:27947) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Mod on _id not allowed

**Comment by karellodewijk** [comment]
I had to look it up. Are you using mongodb <= 2.4 by any chance.

It seems to be caused by some incompatibility between the mongoose library and older mongodb versions. Upgrading mongodb should fix it, probably downgrading mongoose will as well. I use mongodb 3.2 but everything >= 2.6 should work too.

**Comment by KongGal** [comment]
Yeah okay, updated and not it atleast doesn't give me a error, it just doesn't do anything xD :)

**Comment by karellodewijk** [comment]
I'm going to need a link to debug it any further.

**Comment by KongGal** [comment]
http://suicide-squad.cc

**Comment by karellodewijk** [comment]
Well there are obviously some problems with your setup. The main problem is that the server resolves domain as 37.187.29.206:1337, instead of suicide-squad.cc

My guess is you have some kind of reverse proxy like nginx running in front of it that is hiding the host headers from the app. If it is nginx and you have control over it yourself, try:

                proxy_pass http://localhost:1337;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;

Proxy_set_header Host $host; makes certain the host headers are passed and, the upgrade stuff is to make sure it can upgrade a connection to a websocket

**Comment by KongGal** [comment]
You are a life saver! even that fix also helped with with another site :D Thanks a lot!

**Comment by karellodewijk** [comment]
That seems to work fine :)

The last thing you may want to do when hosting for production is letting nginx take care of hosting all the static files: map files/icons/js/css/etc. Add something like this to nginx:

        location /public/ {
                expires 1d;
                root path_to_wottactics/;
        }

and in secrets.txt fill in "static_host": "/public/". You can also move the files from the public folder to a different host altogether and just add the full domain+path in static_host.

**Comment by AdityaRajpal1998** [comment]
I am getting error as

(node:5588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No hostname or hostnames provided in connection string

i am hosting my database from mlab
